networks:
  php_network:
    driver: bridge

services:
  nginx:
    image: nginx:alpine
    container_name: web_nginx
    volumes:
      - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
      - ./application/web:/var/www/html
    ports:
      - ${NGINX_PORT}
    restart: always
    depends_on:
      - web_php
      - web_postgres
    networks:
      - php_network
  web_php:
    build:
      context: ./docker/php
      args:
        XDEBUG_ENABLED: "${XDEBUG_ENABLED}"
        XDEBUG_VERSION: "${XDEBUG_VERSION}"
        PHP_VERSION: "${PHP_VERSION}"
        COMPOSER_VERSION: "${COMPOSER_VERSION}"
    container_name: web_php
    volumes:
      - ./application/web:/var/www/html
    depends_on:
      - web_postgres
    networks:
      - php_network
    extra_hosts:
      - "host.docker.internal:host-gateway"
  web_postgres:
    image: postgres:16.3-alpine3.19
    container_name: web_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./docker/postgres:/docker-entrypoint-initdb.d
      - ./docker/postgres/data:/var/lib/postgresql/data
    networks:
      - php_network
    ports:
      - "5432:5432"